### ISSUE TITLE
G1-5按键疑问

### ISSUE THREAD

**Issue by Babybaby0** [nine-fox/issues#23]
编辑了G键切层后(目标层该键有设置 也是一个G键)，无法还原层，是否G键无法设置为同一个按键

**Comment by nine-fox** [comment]
这个是tmk中的XOR 层状态。

也就是G1切层后，如果再是G2，那么1层和2层同时开启。这时候是2层生效

无法还原的问题已修复，重新刷一次即可。

另外，已经加上了切换层按键。

1.0.8
