### ISSUE TITLE
希望能增加指示当前层的功能

### ISSUE THREAD

**Issue by dovewy** [nine-fox/issues#24]
希望能增加当前层指示功能，比如rgb灯里加一个灯光效果：哪一层显示某种灯光颜色🤪

**Comment by nine-fox** [comment]
不知道现在市面上有别的键盘已经支持了嘛？想参考下

**Comment by dovewy** [comment]
【淘宝】https://m.tb.cn/h.fuqX8H7?tk=pDdw2meXnoW「DOIO 16键 设计师小键盘 三旋钮 客制化 机械键盘 自定义 KB16-01」
点击链接直接打开

doio家是用了个1寸不到小oled屏幕来做到的，我个人感觉是不是也能用电子墨水屏？更省电也不需要刷新率😁



发送自我的盖乐世



-------- 原始信息 --------
发件人： nine-fox ***@***.***>
日期: 2022/6/5 12:15 (GMT+08:00)
收件人： nine-fox/keyboard ***@***.***>
抄送： dovewy ***@***.***>, Author ***@***.***>
主题： Re: [nine-fox/keyboard] 希望能增加指示当前层的功能 (#24)


不知道现在市面上有别的键盘已经支持了嘛？想参考下
