### ISSUE TITLE
希望之城使用触发层的N切换当前层

### ISSUE THREAD

**Issue by 9aoyang** [nine-fox/issues#29]
### 需求场景
比如我的第二层是触发层，第三层是多媒体层，看电影时，希望能切换到多媒体层。

### 操作步骤
1. 按下第一层的M2
1. 按下第二层的N3

### 预期效果
切换到第三层

### 目前表现
会返回第一层

**Comment by nine-fox** [comment]
额。。。嵌套切换目前还不支持。。。。

记录下这个问题先

**Comment by nine-fox** [comment]
上线了宏，应该可以实现了，见

https://nine-fox.com/docs/#/any
