### ISSUE TITLE
不支持优联客制化键盘的按键检测？

### ISSUE THREAD

**Issue by shuosiw** [nine-fox/issues#30]
![image](https://user-images.githubusercontent.com/2578976/79334732-6e6ef500-7f53-11ea-8dc0-9036e97353a1.png)

实际上我已经连接了 优联客制化 的机械键盘，但是软件没有识别出来，显示“请连接键盘...”

本条 issue 也是在我这个键盘输出的，k375s，使用优联无线连接 mac

![image](https://user-images.githubusercontent.com/2578976/79334890-aaa25580-7f53-11ea-9ad7-1b547c525241.png)

跳过这个主页，右下角选择按键测试，到按键测试页面，按键无法被检测到。

已经开通了辅助功能：

![image](https://user-images.githubusercontent.com/2578976/79335030-ee955a80-7f53-11ea-9384-3e01c7aea019.png)

系统：mac os x 10.13.6

**Comment by nine-fox** [comment]
优联协议貌似不是标准的HID协议？这里的按键检测是走的标准usb hid。

**Comment by shuosiw** [comment]
> 优联协议貌似不是标准的HID协议？这里的按键检测是走的标准usb hid。

没办法，我后面用另外的软件的可以测试了...不确定是不是这个原因

**Comment by nine-fox** [comment]
我知道你的意思了，你点错了，要点右下角，切换到按键检测，就行了
